eureka:
    instance:
        hostname: 172.16.0.176
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
    hystrix:
        enabled: false
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.java4all.order.entity
server:
    port: 8083
spring:
    application:
        name: order
    cloud:
        alibaba:
            seata:
                tx-service-group: ${spring.application.name}-seata-tx-service-group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seat-order
        username: root
        password: root