eureka:
    instance:
        hostname: 172.16.0.176
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.java4all.storage.entity
server:
    port: 8082
spring:
    application:
        name: storage
    cloud:
        alibaba:
            seata:
                tx-service-group: ${spring.application.name}-seata-tx-service-group
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seat-storage
        username: root
        password: root